version: '3.9'

networks:
  development:
  test:

volumes:
  db_data:
  gem_cache:
  shared_data:

services:
  spotiit_redis:
    image: redis:4.0-alpine
    command: redis-server
    networks:
      - development
      - test
    volumes:
      - shared_data:/var/shared/redis

  spotiit_db:
    image: postgres:12.5-alpine
    container_name: spotiit_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      #- 5099:5432
      - 5432:5432

  spotiit_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: spotiit_app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - spotiit_db

  spotiit_test:
    image: spotiit_spotiit_app
    container_name: spotiit_test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    environment:
      RAILS_ENV: test
    depends_on:
      - spotiit_db
