Type.create(sector: 'immo', catetory: 'sharedfeatures', typeName: 'Ascenseur', typekey: 'lift')
Type.create(sector: 'immo', catetory: 'sharedfeatures', typeName: 'Etage', typekey: 'floor')
Type.create(sector: 'immo', catetory: 'sharedfeatures', typeName: 'Accès handicapé', typekey: 'ramp')
Type.create(sector: 'immo', catetory: 'sharedfeatures', typeName: 'Gardien', typekey: 'caretaker')
Type.create(sector: 'immo', catetory: 'sharedfeatures', typeName: 'Parking', typekey: 'parking')
Type.create(sector: 'immo', catetory: 'sharedfeatures', typeName: 'Cave', typekey: 'cellar')
Type.create(sector: 'immo', catetory: 'sharedfeatures', typeName: 'Box', typekey: 'lockup')
Type.create(sector: 'immo', catetory: 'sharedfeatures', typeName: 'Fibre', typekey: 'fiber')
Type.create(sector: 'immo', catetory: 'outsidefeatures', typeName: 'Balcon', typekey: 'balcony')
Type.create(sector: 'immo', catetory: 'outsidefeatures', typeName: 'Terrasse', typekey: 'terrace')
Type.create(sector: 'immo', catetory: 'outsidefeatures', typeName: 'Jardin', typekey: 'garden')
Type.create(sector: 'immo', catetory: 'outsidefeatures', typeName: 'Piscine', typekey: 'pool')
Type.create(sector: 'immo', catetory: 'outsidefeatures', typeName: 'Piscinable', typekey: 'poolable')
Type.create(sector: 'immo', catetory: 'outsidefeatures', typeName: 'dependance', typekey: 'outhouse')
Type.create(sector: 'immo', catetory: 'insidefeatures', typeName: 'Cheminée', typekey: 'fireplace')
Type.create(sector: 'immo', catetory: 'insidefeatures', typeName: 'Parquet', typekey: 'woodenfloor')
Type.create(sector: 'immo', catetory: 'insidefeatures', typeName: 'WC séparés', typekey: 'separatewc')
Type.create(sector: 'immo', catetory: 'insidefeatures', typeName: 'Rangements', typekey: 'storage')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Appartement', typekey: 'Appartment')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Maison', typekey: 'House')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Loft/atelier', typekey: 'Loft/Workshop')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'parking/box', typekey: 'Parking / Box')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Château ', typekey: 'Castle')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Hotel', typekey: 'Mansion')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Gite ', typekey: 'Gite')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Chalet mobil home', typekey: 'Chalet-Mobil-Home')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Immeuble', typekey: 'Building')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'peniche', typekey: 'Barge')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'local commecial', typekey: 'Commercial premises')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Bureaux', typekey: 'Offices and professional premises')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'fond de commerce', typekey: 'Commercial property')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'local d acivité', typekey: 'Activity premises')
Type.create(sector: 'immo', catetory: 'propertytypes', typeName: 'Divers', typekey: 'Various')
Type.create(sector: 'immo', catetory: 'propertystates', typeName: 'Neuf< 5', typekey: 'recent')
Type.create(sector: 'immo', catetory: 'propertystates', typeName: 'Ancien', typekey: 'old')
Type.create(sector: 'immo', catetory: 'propertystates', typeName: 'Viager', typekey: 'lifeannuity')
Type.create(sector: 'immo', catetory: 'propertystates', typeName: 'Construire/Vefa', typekey: 'offplan')
Type.create(sector: 'immo', catetory: 'propertydetails', typeName: 'Surface habitable ', typekey: 'livingarea')
Type.create(sector: 'immo', catetory: 'propertydetails', typeName: 'Surface terrain min', typekey: 'landarea')
Type.create(sector: 'immo', catetory: 'propertydetails', typeName: 'Nombre de pièces ', typekey: 'rooms')
Type.create(sector: 'immo', catetory: 'propertydetails', typeName: 'Nombre de chambres', typekey: 'bedrooms')
Type.create(sector: 'immo', catetory: 'propertylocations', typeName: 'Villes', typekey: 'cities')
Type.create(sector: 'immo', catetory: 'propertylocations', typeName: 'Départements', typekey: 'dept')
Type.create(sector: 'immo', catetory: 'propertylocations', typeName: 'Lieu + km', typekey: 'area')